[package]
name = "todo_journal"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
structopt = "0.3.26"

[dependencies.chrono]
features = ["serde"]
version = "0.4.38"

[dependencies.serde]
features = ["derive"]
version = "1.0.203"